---
- name: Install GPG
  package:
    name: gpg
    state: present
  tags:
    - role::filebeat

- name: Install Elasticsearch signing key
  # noqa command-instead-of-module
  shell: >-
    set -o pipefail && wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch |
    gpg --yes --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags:
    - role::filebeat

- name: Add Elasticsearch repository to apt
  copy:
    content: >-
      deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg]
      https://artifacts.elastic.co/packages/8.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    owner: root
    group: root
    mode: 0644
  tags:
    - role::filebeat
  register: add_filebeat_repo

- name: Install Filebeat
  apt:
    pkg: filebeat
    state: present
    update_cache: "{{ add_filebeat_repo.changed }}"
  tags:
    - role::filebeat

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
    owner: root
    group: root
  tags:
    - role::filebeat
  notify:
    - restart filebeat

- name: Start and enable Filebeat
  service:
    name: filebeat
    state: started
    enabled: true
  tags:
    - role::filebeat
