---
- name: Install Filebeat
  apt:
    pkg: filebeat
    state: present
  tags:
    - role::filebeat

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
    owner: root
    group: root
  tags:
    - role::filebeat
  notify:
    - restart filebeat

- name: Start and enable Filebeat
  service:
    name: filebeat
    state: started
    enabled: true
  tags:
    - role::filebeat
