---
- name: Install Kibana
  apt:
    pkg: kibana
    state: present
  tags:
    - role::kibana

- name: Configure Kibana base URL
  lineinfile:
    path: /etc/kibana/kibana.yml
    state: present
    line: "server.publicBaseUrl: {{ kibana_public_url }}"
  tags:
    - role::kibana

- name: Start and enable Kibana
  service:
    name: kibana
    state: started
    enabled: true
  tags:
    - role::kibana
