---
- name: Install GPG
  package:
    name: gpg
    state: present
  tags:
    - role::kibana

- name: Install Elasticsearch signing key
  # noqa command-instead-of-module
  shell: >-
    set -o pipefail && wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch |
    gpg --yes --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags:
    - role::kibana

- name: Add Elasticsearch repository to apt
  copy:
    content: >-
      deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg]
      https://artifacts.elastic.co/packages/8.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    owner: root
    group: root
    mode: 0644
  tags:
    - role::kibana
  register: add_kibana_repo

- name: Install Kibana
  apt:
    pkg: kibana
    state: present
    update_cache: "{{ add_kibana_repo.changed }}"
  tags:
    - role::kibana

- name: Configure Kibana base URL
  lineinfile:
    path: /etc/kibana/kibana.yml
    state: present
    line: "server.publicBaseUrl: {{ kibana_public_url }}"
  tags:
    - role::kibana

- name: Start and enable Kibana
  service:
    name: kibana
    state: started
    enabled: true
  tags:
    - role::kibana
