---
- name: Install Packetbeat
  apt:
    pkg: packetbeat
    state: present
  tags:
    - role::packetbeat

- name: Configure Packetbeat
  template:
    src: packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
    mode: 0644
    owner: root
    group: root
  tags:
    - role::packetbeat
  notify:
    - restart packetbeat

- name: Start and enable Packetbeat
  service:
    name: packetbeat
    state: started
    enabled: true
  tags:
    - role::packetbeat
