---
- name: Install GPG
  package:
    name: gpg
    state: present
  tags:
    - role::elasticsearch

- name: Install Elasticsearch signing key
  # noqa command-instead-of-module
  shell: >-
    set -o pipefail && wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch |
    gpg --yes --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags:
    - role::elasticsearch

- name: Add Elasticsearch repository to apt
  copy:
    content: >-
      deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg]
      https://artifacts.elastic.co/packages/8.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    owner: root
    group: root
    mode: 0644
  tags:
    - role::elasticsearch
  register: add_elastic_repo

- name: Install Elasticsearch
  apt:
    pkg: elasticsearch
    state: present
    update_cache: "{{ add_elastic_repo.changed }}"
  tags:
    - role::elasticsearch

- name: Start and enable Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
  tags:
    - role::elasticsearch
