---
- name: Install Elasticsearch
  apt:
    pkg: elasticsearch
    state: present
  tags:
    - role::elasticsearch

- name: Start and enable Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
  tags:
    - role::elasticsearch
